package com.example.BAS.enumerations;

public enum Status {
    AFGEROND,
    BIJZONDERHEID,
    RETOUR,
    WACHTEN_OP_PSK_EN_BEDRAG,
    WACHTEN_OP_PSK,
    WACHTEN_OP_BEDRAG,
    WACHTEN_OP_PSK_EN_BEDRAG_ALLEEN_AKKOORD_BIJ_GEEN_INLEG_NA_2014,
    WACHTEN_OP_PSK_ALLEEN_AKKOORD_BIJ_GEEN_INLEG_NA_2014,
}
